package.json, src/index.d.ts
For usage with Typescript, this declares the function signature of the hook.
=> add typescript typings

README.md
Fixed example of `useDebouncedCallback` usage.
=> Fixed usage of useDebouncedCallback in README

README.md
While the current form of import works in JS, it doesn't in TS. It is also an internal implementation detail, and not part of the external API.
This PR fixes the docs to reflect the correct import for `useDebouncedCallback`. :wrench:
=> Fix `useDebouncedCallback` import docs

README.md, src/cache.ts, src/callback.ts, test/cache.test.tsx, test/callback.test.tsx
Allow values and callbacks to be invoked immediately through a new `leading` option. This behaves similarly to the Lodash implementation: https://lodash.com/docs/#debounce
Great library by the way! Super useful for the project I'm currently working on 😃
=> Add a `leading` option

.gitignore, package.json, tsconfig.json
Right now, the library is not tree shakeable. These changes will enable tree shaking.
=> Emit code in ESM format

.npmignore, package.json
It makes sense to include only the necessary minimum set of files in the package to reduce the package size:
1. `esm`
2. `lib`
3. `CHANGELOG.md`
4. `LICENSE`
5. `package.json`
6. `README.md`
For comparison:
Also I use the `files` package.json property instead of `.npmignore` иecause I think it's a better approach. Motivation: https://medium.com/@jdxcode/for-the-love-of-god-dont-use-npmignore-f93c08909d8d.
=> Include only necessary file in the npm package

src/useDebounce.ts, test/useDebounce.test.tsx
This PR adds an optional parameter to `useDebounce` that can be used to provide a custom equality function (e.g. an equality function for deep object comparison) to the hook. It defaults to a simple strict equality comparison.
Let me know what you think 😄
=> Allow custom equality function in useDebounce

src/useDebounce.ts, src/useDebouncedCallback.ts
Hi, thank you for nice library.
I found return type of `useDebouncedCallback` is wrong.
Given `(T) => P` as callback, `debouncedCallback` never returns `P` (or anything), so signature of `debouncedCallback ` should be `(T) => void`, but currently its signature is `(T) => P`. With this p-r, `debouncedCallback` will have `(T) => void` signature, matching with actual behavior.
(And additionally I removed explicit type annotations for `useRef` since it's not necessary. )
Note:
- This p-r changes only type annotations, therefore the compiled JS will not change
- This p-r may cause type check errors in users' codes since type signature changes
- But I should change it anyway, because current signature is wrong
=> Fix typings (especially return type of useDebouncedCallback)

package.json
Hi~
When I actually used it, I found other old files in the npm package.
Of course, this does not affect the actual use.
But I feel it can be avoided automatically. Of course, you can delete it manually. :)
Thanks~ 🙋‍♂️
=> chore(build): del old cache

package.json, src/useDebouncedCallback.ts, test/useDebounce.test.tsx, test/useDebouncedCallback.test.tsx, yarn.lock
- Addresses https://github.com/xnimorz/use-debounce/issues/60
- Changes `useDebouncedCallback` to mirror [lodash's implementation of debounce](https://github.com/lodash/lodash/blob/86a852fe763935bb64c12589df5391fd7d3bb14d/debounce.js).
- Verified that the behaviour matches lodash with [this jsfiddle](https://jsfiddle.net/t2wkacq9/201/)
- Support using rAF when omitting `wait`
- Ability to implement throttling without trailing edge call 
- `wait: 200, {leading: true, trailing: false, maxWait: 200}`
This is a lot of changes to the source code but it was easier to start with lodash code and work backwards from there. Let me know what you think.
**Things to note**
- The requestAnimationFrame is accessed via `window.requestAnimationFrame`. I'm not an experienced library author so I'm not sure …
=> Complete support for leading, trailing, maxWait

src/useDebouncedCallback.ts
Round 2.
`cancel` is the only function that calls `cancelCallback`, so it doesn't make a lot of sense to have two callbacks instead of one. I just merged them. 
–12 bytes:
```diff
-  Size:       896 B with all dependencies, minified and gzipped
+  Size:       884 B with all dependencies, minified and gzipped
-  Size:       857 B with all dependencies, minified and gzipped
+  Size:       846 B with all dependencies, minified and gzipped
-  Size:       740 B with all dependencies, minified and gzipped
+  Size:       728 B with all dependencies, minified and gzipped
```
=> Optimization: extra callback

src/useDebouncedCallback.ts
Round 3 (~ –13 bytes)
Replacing strict `timerId` conditions with short truthy/falsy ones:
```js
timerId === undefined → !timerId
timerId !== undefined → timerId
```
Why? Because `setTimeout` and `requestAnimationFrame` don't return zero (or returns an object in NodeJS), so any `timerId` you have is passing the truthy conditions.
https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout
> The returned timeoutID is **a positive integer value**
https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame
> A long integer value, the request id, that uniquely identifies the entry in the callback list. **This is a non-zero value**...
```diff
-  Size:       896 B with all dependencies, minified and gzipped
+  Size:       882 B with all dependencies, …
```
=> Optimization: timerId conditions

src/useDebounce.ts, src/useDebouncedCallback.ts
Round 4: (~ –11 bytes)
1. Replaced most of `useRef(undefined)` with `useRef()` since it's the same.
2. Replaced `undefined` with `null` almost everywhere since it's also falsy and 2+ times shorter.
3. Replaced `Number(n)` value conversions with `+n` since it works the same way. Even [lodash uses](https://github.com/lodash/lodash/blob/master/debounce.js#L84) `+` in their latest versions.
```diff
-  Size:       873 B with all dependencies, minified and gzipped
+  Size:       862 B with all dependencies, minified and gzipped
-  Size:       837 B with all dependencies, minified and gzipped
+  Size:       825 B with all dependencies, minified and gzipped
-  Size:       718 B with all dependencies, minified and gzipped
+  Size:       710 B with all dependencies, minified and gzipped
```
=> Optimization: Type juggling

src/useDebouncedCallback.ts
Round 6: **(~ –11 bytes)**
Merge two callbacks into one in order to reduce the number of useCallback+deps declarations.
```diff
-  Size:       853 B with all dependencies, minified and gzipped
+  Size:       844 B with all dependencies, minified and gzipped
-  Size:       817 B with all dependencies, minified and gzipped
+  Size:       808 B with all dependencies, minified and gzipped
-  Size:       700 B with all dependencies, minified and gzipped
+  Size:       693 B with all dependencies, minified and gzipped
```
=> Optimization: Move `remainingWait` to `timerExpired`

src/useDebouncedCallback.ts
Round 7: **(~ –18 bytes)**
1. We don't need default `options` value because you check and set the default values for `leading` and `trailing` anyway (see lines 41-42).
2. Moved `timerId.current = ` assingment inside of `startTimer` to reduce code duplication
3. Combined return and assignment statements into one line.
```diff
-  Size:       844 B with all dependencies, minified and gzipped
+  Size:       826 B with all dependencies, minified and gzipped
-  Size:       808 B with all dependencies, minified and gzipped
+  Size:       790 B with all dependencies, minified and gzipped
-  Size:       693 B with all dependencies, minified and gzipped
+  Size:       675 B with all dependencies, minified and gzipped
```
=> Optimization: shorten `useDebouncedCallback` code a bit

CHANGELOG.md
Update v5 upgrade text in changelog. 
It was using `useDebouncedCallback` instead of `useDebounce` when showing how `useDebounce` return value has changed between versions
=> Fix v5 upgrade instructions for useDebounce case

src/useDebouncedCallback.ts, src/useThrottledCallback.ts
Give more information in code editors like VSCode when hovering over types.
| Before | After |
| -| -|
| long sentence ![image](https://user-images.githubusercontent.com/2373958/178976437-8509cb47-1bd2-4a20-8175-b75d42451d6f.png) | broken into multiple sentence ![image](https://user-images.githubusercontent.com/2373958/178976341-32c27cbc-49ae-41f9-b672-174e75f95463.png) |
| Before | After |
| -| -|
| no context around options ![image](https://user-images.githubusercontent.com/2373958/178976478-67c92222-3257-4595-863a-aa3746276481.png) | type hint indicating what this option does ![image](https://user-images.githubusercontent.com/2373958/178976410-6ab85206-3e63-43aa-8356-42edfde45300.png) |
=> Improve code comment docs

src/index.ts
This is useful for example when declaring a custom hook that returns a denounced function and the code-base enforces explicitly declared return types.
```tsx
import type { DebouncedState } from 'use-debounced';
type Result = DebouncedState<React.ChangeEventHandler<HTMLInputElement>>;
export const useProgressBarStepping = (): Result => {
const onChange = useDebouncedCallback(
(event: React.ChangeEvent<HTMLInputElement>): void => {
// ...
},
100,
{ maxWait: 200 },
);
return onChange;
};
```
Especially since it's impossible to extract `DebouncedState` via Typescript version lower than v4.7. See
https://stackoverflow.com/questions/50321419/typescript-returntype-of-generic-function
=> export types from package

package.json
To find the types for a package,  typescript uses a rule where it finds the ".js" file
for the import and then changes the extension to ".d.ts".
For typescript versions 4.6 and below and typescript 4.7 with moduleResolution "node",
typescript is looking at the "require" entry in "exports" and therefore finds "./dist/index.js"
and then looks for "./dist/index.d.ts" to find the types.  This file exists so everything works.
For typescript 4.7 with node16 module resolution, typescript is now looking at the "module"
field and finding "./dist/index.module.js".  Typescript then searches for a file "./dist/index.module.d.ts"
to find types, but that file does not exist and typescript produces an error
error TS7016: Could not find a declaration file for module 'use-debounce'.
The fix is just to …
=> Update package.json to support typescript node16

src/useDebouncedCallback.ts
The types are failing if the function is used with other generic functions.
For example type `<Args extends Array<unknown>` fails this check.
A minimal example of the failing types that this change would fix:
```ts
import type { ActionCreatorWithPreparedPayload } from "@reduxjs/toolkit";
import { useDispatch } from "react-redux";
import { useDebouncedCallback } from "use-debounce";
interface UseFilterUpdaterParams<Args extends Array<unknown>, Payload> {
updateFunction: ActionCreatorWithPreparedPayload<Args, Payload>;
DEBOUNCED_HANDLER_MS?: number;
}
const useUpdater = <Args extends Array<unknown>, Payload>({
updateFunction,
DEBOUNCED_HANDLER_MS = 0,
}: UseFilterUpdaterParams<Args, Payload>) => {
const dispatch = useDispatch();
/**
* Argument of type '(...props: Args) => void' is not …
```
=> Simplify extended useDebouncedCallback function types

.github/workflows/main.yml, package.json, yarn.lock
Cannot update further as size-limit is using webpack 4.44, which uses deprecated node API for hashing
=> Update nove version for github actions to 16.x

src/useDebounce.ts, test/useDebounce.test.tsx
The return type now correctly reflects that the second item can be called manually as a debounced setter, which is super useful in certain situations.
=> Represent correct return type from useDebounce()

src/useDebouncedCallback.ts, src/useThrottledCallback.ts
Hi, I'm having some problems customizing types.
```
Type '(...args: Parameters<T>) => Promise<void>' does not satisfy the constraint '(...args: any[]) => Promise<void>'
```
like
```ts
export type ReturnResultType<T extends (...args: any) => ReturnType<T>> = {
callback: DebouncedState<(...args: Parameters<T>) => Promise<void>>;
};
```
So I want to lift the restriction on the array type of function parameters, same as `Parameters`
```ts
/**
* Obtain the parameters of a function type in a tuple
*/
type Parameters<T extends (...args: any) => any> = T extends (...args: infer P) => any ? P : never;
```
=> refactor(type): function parameters type

package.json
My main motivation behind this PR was to fix `types`. When using this package without `node` and `browser` conditions the types couldn't be found.
I've reexamined the structure of the declared `exports` and I concluded that they are a little bit over-engineered since, as far as I can tell, you are actually not shipping any env-specific code. So it should be possible to simplify this to only those basic~ conditions
=> Tweak `package.json#exports` manifest

src/useDebouncedCallback.ts, src/useThrottledCallback.ts
The callback property in the `DebouncedState` interface has been removed [over 2 year ago](https://github.com/koenpunt/use-debounce/commit/045f960583ea37dc4a55df4ed7e542f1a1f0a05a).
=> Remove incorrect docblock about obsolete .callback property

src/useDebouncedCallback.ts, test/useDebouncedCallback.test.tsx
The `flush()` function returns the result of the most recent function invocation, however, the type declaration did not reflect this correctly. This PR updates the Typescript declaration to match the actual return-type of the function.
Fixes #174
=> Fix type declaration for flush()

src/useDebouncedCallback.ts
Hi there! I'm pretty sure `.pending()` hasn't existed in a while, but is still shown in the TSDoc for `useDebouncedCallback`. Here's a fix!
=> Update outdated tsdoc for useDebouncedCallback
